#
# Generales
#
scribo:
    pattern:  /
    defaults: { _controller: ScriboBundle:Default:index }
scribo_login:
    pattern:  /login
    defaults: { _controller: ScriboBundle:Default:login }
scribo_logout:
    pattern:  /logout
    defaults: { _controller: ScriboBundle:Default:logout }
scribo_chpass:
    pattern:  /chpass
    defaults: { _controller: ScriboBundle:Default:chpass }
#
# Procesos
#
scribo_home:
    pattern:  /home
    defaults: { _controller: ScriboBundle:Home:index }
scribo_home_list:
    pattern:  /home/list
    defaults: { _controller: ScriboBundle:Home:list }
scribo_home_proc:
    pattern:  /home/proc
    defaults: { _controller: ScriboBundle:Home:proc }
scribo_home_reciv:
    pattern:  /home/reciv
    defaults: { _controller: ScriboBundle:Home:reciv }
scribo_home_cicle:
    pattern:  /home/cicle
    defaults: { _controller: ScriboBundle:Home:cicle }
scribo_home_veri:
    pattern:  /home/veri
    defaults: { _controller: ScriboBundle:Home:veri }
scribo_home_entrega:
    pattern:  /home/entrega
    defaults: { _controller: ScriboBundle:Home:entrega }
scribo_home_visor:
    pattern:  /home/{id}/visor
    defaults: { _controller: ScriboBundle:Home:visor }
scribo_home_docu:
    pattern:  /home/{id}/docu
    defaults: { _controller: ScriboBundle:Home:docu }
#
# Board
#
scribo_board:
    pattern:  /board
    defaults: { _controller: ScriboBundle:Board:index }
scribo_board_pro:
    pattern:  /board/pro
    defaults: { _controller: ScriboBundle:Board:pro }
scribo_board_list:
    pattern:  /board/list
    defaults: { _controller: ScriboBundle:Board:list }
scribo_board_listp:
    pattern:  /board/listp
    defaults: { _controller: ScriboBundle:Board:listp }
#
# Personal
#
scribo_personal:
    pattern:  /pers
    defaults: { _controller: ScriboBundle:Personal:index }
scribo_personal_save:
    pattern:  /pers/save
    defaults: { _controller: ScriboBundle:Personal:save }
scribo_personal_list:
    pattern:  /pers/enum
    defaults: { _controller: ScriboBundle:Personal:enum }
scribo_personal_get:
    pattern:  /pers/get
    defaults: { _controller: ScriboBundle:Personal:get }
scribo_personal_del:
    pattern:  /pers/del
    defaults: { _controller: ScriboBundle:Personal:del }
scribo_personal_find:
    pattern:  /pers/find
    defaults: { _controller: ScriboBundle:Personal:find }
#
# Usuarios
#
scribo_usuario:
    pattern:  /usua
    defaults: { _controller: ScriboBundle:Usuario:index }
scribo_usuario_save:
    pattern:  /usua/save
    defaults: { _controller: ScriboBundle:Usuario:save }
scribo_usuario_list:
    pattern:  /usua/enum
    defaults: { _controller: ScriboBundle:Usuario:enum }
scribo_usuario_get:
    pattern:  /usua/get
    defaults: { _controller: ScriboBundle:Usuario:get }
scribo_usuario_del:
    pattern:  /usua/del
    defaults: { _controller: ScriboBundle:Usuario:del }
#
# Clientes
#
scribo_cliente:
    pattern:  /clie
    defaults: { _controller: ScriboBundle:Cliente:index }
scribo_cliente_save:
    pattern:  /clie/save
    defaults: { _controller: ScriboBundle:Cliente:save }
scribo_cliente_list:
    pattern:  /clie/enum
    defaults: { _controller: ScriboBundle:Cliente:enum }
scribo_cliente_get:
    pattern:  /clie/get
    defaults: { _controller: ScriboBundle:Cliente:get }
scribo_cliente_del:
    pattern:  /clie/del
    defaults: { _controller: ScriboBundle:Cliente:del }
#
# Materiales
#
scribo_material:
    pattern:  /mate
    defaults: { _controller: ScriboBundle:Material:index }
scribo_material_save:
    pattern:  /mate/save
    defaults: { _controller: ScriboBundle:Material:save }
scribo_material_list:
    pattern:  /mate/enum
    defaults: { _controller: ScriboBundle:Material:enum }
scribo_material_get:
    pattern:  /mate/get
    defaults: { _controller: ScriboBundle:Material:get }
scribo_material_del:
    pattern:  /mate/del
    defaults: { _controller: ScriboBundle:Material:del }
#
# Acabados
#
scribo_acabado:
    pattern:  /acab
    defaults: { _controller: ScriboBundle:Acabado:index }
scribo_acabado_save:
    pattern:  /acab/save
    defaults: { _controller: ScriboBundle:Acabado:save }
scribo_acabado_list:
    pattern:  /acab/enum
    defaults: { _controller: ScriboBundle:Acabado:enum }
scribo_acabado_get:
    pattern:  /acab/get
    defaults: { _controller: ScriboBundle:Acabado:get }
scribo_acabado_del:
    pattern:  /acab/del
    defaults: { _controller: ScriboBundle:Acabado:del }
#
# Tintas
#
scribo_tinta:
    pattern:  /tint
    defaults: { _controller: ScriboBundle:Tinta:index }
scribo_tinta_save:
    pattern:  /tint/save
    defaults: { _controller: ScriboBundle:Tinta:save }
scribo_tinta_list:
    pattern:  /tint/enum
    defaults: { _controller: ScriboBundle:Tinta:enum }
scribo_tinta_get:
    pattern:  /tint/get
    defaults: { _controller: ScriboBundle:Tinta:get }
scribo_tinta_del:
    pattern:  /tint/del
    defaults: { _controller: ScriboBundle:Tinta:del }
#
# Configuración
#
scribo_config:
    pattern:  /conf
    defaults: { _controller: ScriboBundle:Config:index }
scribo_config_save:
    pattern:  /conf/save
    defaults: { _controller: ScriboBundle:Config:save }
#
# G. De Ficheros
#
scribo_filer:
    pattern:  /filer
    defaults: { _controller: ScriboBundle:Filer:index }
scribo_filer_list:
    pattern:  /filer/list
    defaults: { _controller: ScriboBundle:Filer:list }
scribo_filer_purge:
    pattern:  /filer/purge
    defaults: { _controller: ScriboBundle:Filer:purge }
scribo_filer_update:
    pattern:  /filer/update
    defaults: { _controller: ScriboBundle:Filer:update }
scribo_filer_delete:
    pattern:  /filer/delete
    defaults: { _controller: ScriboBundle:Filer:delete }
#
# Orden Tipo 1
#
scribo_uno:
    pattern:  /uno
    defaults: { _controller: ScriboBundle:Uno:index }
scribo_uno_findcli:
    pattern:  /uno/ordclient
    defaults: { _controller: ScriboBundle:Uno:fcli }
scribo_uno_findmate:
    pattern:  /uno/ordmaterial
    defaults: { _controller: ScriboBundle:Uno:fmate }
scribo_uno_findtinta:
    pattern:  /uno/ordtinta
    defaults: { _controller: ScriboBundle:Uno:ftinta }
scribo_uno_findacabado:
    pattern:  /uno/ordacabado
    defaults: { _controller: ScriboBundle:Uno:facabado }
scribo_uno_save:
    pattern:  /uno/save
    defaults: { _controller: ScriboBundle:Uno:save }
scribo_uno_visor:
    pattern:  /uno/{id}/visor
    defaults: { _controller: ScriboBundle:Uno:visor }
scribo_uno_docu:
    pattern:  /uno/{id}/docu
    defaults: { _controller: ScriboBundle:Uno:docu }
#
# Orden Tipo 2
#
scribo_dos:
    pattern:  /dos
    defaults: { _controller: ScriboBundle:Dos:index }
scribo_dos_findcli:
    pattern:  /dos/ordclient
    defaults: { _controller: ScriboBundle:Dos:fcli }
scribo_dos_findmate:
    pattern:  /dos/ordmaterial
    defaults: { _controller: ScriboBundle:Dos:fmate }
scribo_dos_findtinta:
    pattern:  /dos/ordtinta
    defaults: { _controller: ScriboBundle:Dos:ftinta }
scribo_dos_findacabado:
    pattern:  /dos/ordacabado
    defaults: { _controller: ScriboBundle:Dos:facabado }
scribo_dos_save:
    pattern:  /dos/save
    defaults: { _controller: ScriboBundle:Dos:save }
scribo_dos_visor:
    pattern:  /dos/{id}/visor
    defaults: { _controller: ScriboBundle:Dos:visor }
scribo_dos_docu:
    pattern:  /dos/{id}/docu
    defaults: { _controller: ScriboBundle:Dos:docu }
#
# Reporte
#
scribo_repo:
    pattern:  /repo
    defaults: { _controller: ScriboBundle:Repo:index }
scribo_repo_enday:
    pattern:  /repo/{D}/enday
    defaults: { _controller: ScriboBundle:Repo:enDay }
scribo_repo_enweek:
    pattern:  /repo/{D}/enweek
    defaults: { _controller: ScriboBundle:Repo:enWeek }
scribo_repo_enmonth:
    pattern:  /repo/{D}/enmonth
    defaults: { _controller: ScriboBundle:Repo:enMonth }
scribo_repo_enyear:
    pattern:  /repo/{D}/enyear
    defaults: { _controller: ScriboBundle:Repo:enYear }
scribo_repo_endeca:
    pattern:  /repo/{D}/endeca
    defaults: { _controller: ScriboBundle:Repo:enDeca }
