#
# Generales
#
scribo:
    pattern:  /
    defaults: { _controller: ScriboBundle:Default:index }
scribo_login:
    pattern:  /login
    defaults: { _controller: ScriboBundle:Default:login }
scribo_logout:
    pattern:  /logout
    defaults: { _controller: ScriboBundle:Default:logout }
scribo_chpass:
    pattern:  /chpass
    defaults: { _controller: ScriboBundle:Default:chpass }
scribo_home:
    pattern:  /home
    defaults: { _controller: ScriboBundle:Home:index }
#
# Personal
#
scribo_personal:
    pattern:  /pers
    defaults: { _controller: ScriboBundle:Personal:index }
scribo_personal_save:
    pattern:  /pers/save
    defaults: { _controller: ScriboBundle:Personal:save }
scribo_personal_save:
    pattern:  /pers/save
    defaults: { _controller: ScriboBundle:Personal:save }
scribo_personal_list:
    pattern:  /pers/enum
    defaults: { _controller: ScriboBundle:Personal:enum }
scribo_personal_get:
    pattern:  /pers/get
    defaults: { _controller: ScriboBundle:Personal:get }
scribo_personal_del:
    pattern:  /pers/del
    defaults: { _controller: ScriboBundle:Personal:del }
scribo_personal_find:
    pattern:  /pers/find
    defaults: { _controller: ScriboBundle:Personal:find }
#
# Usuarios
#
scribo_usuario:
    pattern:  /usua
    defaults: { _controller: ScriboBundle:Usuario:index }
scribo_usuario_save:
    pattern:  /usua/save
    defaults: { _controller: ScriboBundle:Usuario:save }
scribo_usuario_save:
    pattern:  /usua/save
    defaults: { _controller: ScriboBundle:Usuario:save }
scribo_usuario_list:
    pattern:  /usua/enum
    defaults: { _controller: ScriboBundle:Usuario:enum }
scribo_usuario_get:
    pattern:  /usua/get
    defaults: { _controller: ScriboBundle:Usuario:get }
scribo_usuario_del:
    pattern:  /usua/del
    defaults: { _controller: ScriboBundle:Usuario:del }
#
# Clientes
#
scribo_cliente:
    pattern:  /clie
    defaults: { _controller: ScriboBundle:Cliente:index }
scribo_cliente_save:
    pattern:  /clie/save
    defaults: { _controller: ScriboBundle:Cliente:save }
scribo_cliente_save:
    pattern:  /clie/save
    defaults: { _controller: ScriboBundle:Cliente:save }
scribo_cliente_list:
    pattern:  /clie/enum
    defaults: { _controller: ScriboBundle:Cliente:enum }
scribo_cliente_get:
    pattern:  /clie/get
    defaults: { _controller: ScriboBundle:Cliente:get }
scribo_cliente_del:
    pattern:  /clie/del
    defaults: { _controller: ScriboBundle:Cliente:del }
#
# Materiales
#
scribo_material:
    pattern:  /mate
    defaults: { _controller: ScriboBundle:Material:index }
scribo_material_save:
    pattern:  /mate/save
    defaults: { _controller: ScriboBundle:Material:save }
scribo_material_save:
    pattern:  /mate/save
    defaults: { _controller: ScriboBundle:Material:save }
scribo_material_list:
    pattern:  /mate/enum
    defaults: { _controller: ScriboBundle:Material:enum }
scribo_material_get:
    pattern:  /mate/get
    defaults: { _controller: ScriboBundle:Material:get }
scribo_material_del:
    pattern:  /mate/del
    defaults: { _controller: ScriboBundle:Material:del }
