#
# Generales
#
scribo:
    pattern:  /
    defaults: { _controller: ScriboBundle:Default:index }
scribo_login:
    pattern:  /login
    defaults: { _controller: ScriboBundle:Default:login }
scribo_logout:
    pattern:  /logout
    defaults: { _controller: ScriboBundle:Default:logout }
scribo_chpass:
    pattern:  /chpass
    defaults: { _controller: ScriboBundle:Default:chpass }
scribo_home:
    pattern:  /home
    defaults: { _controller: ScriboBundle:Home:index }
#
# Personal
#
scribo_personal:
    pattern:  /pers
    defaults: { _controller: ScriboBundle:Personal:index }
scribo_personal_save:
    pattern:  /pers/save
    defaults: { _controller: ScriboBundle:Personal:save }
scribo_personal_save:
    pattern:  /pers/save
    defaults: { _controller: ScriboBundle:Personal:save }
scribo_personal_list:
    pattern:  /pers/enum
    defaults: { _controller: ScriboBundle:Personal:enum }
scribo_personal_get:
    pattern:  /pers/get
    defaults: { _controller: ScriboBundle:Personal:get }
scribo_personal_del:
    pattern:  /pers/del
    defaults: { _controller: ScriboBundle:Personal:del }
scribo_personal_find:
    pattern:  /pers/find
    defaults: { _controller: ScriboBundle:Personal:find }
#
# Usuarios
#
scribo_usuario:
    pattern:  /usua
    defaults: { _controller: ScriboBundle:Usuario:index }
scribo_usuario_save:
    pattern:  /usua/save
    defaults: { _controller: ScriboBundle:Usuario:save }
scribo_usuario_save:
    pattern:  /usua/save
    defaults: { _controller: ScriboBundle:Usuario:save }
scribo_usuario_list:
    pattern:  /usua/enum
    defaults: { _controller: ScriboBundle:Usuario:enum }
scribo_usuario_get:
    pattern:  /usua/get
    defaults: { _controller: ScriboBundle:Usuario:get }
scribo_usuario_del:
    pattern:  /usua/del
    defaults: { _controller: ScriboBundle:Usuario:del }
#
# Clientes
#
scribo_cliente:
    pattern:  /clie
    defaults: { _controller: ScriboBundle:Cliente:index }
scribo_cliente_save:
    pattern:  /clie/save
    defaults: { _controller: ScriboBundle:Cliente:save }
scribo_cliente_save:
    pattern:  /clie/save
    defaults: { _controller: ScriboBundle:Cliente:save }
scribo_cliente_list:
    pattern:  /clie/enum
    defaults: { _controller: ScriboBundle:Cliente:enum }
scribo_cliente_get:
    pattern:  /clie/get
    defaults: { _controller: ScriboBundle:Cliente:get }
scribo_cliente_del:
    pattern:  /clie/del
    defaults: { _controller: ScriboBundle:Cliente:del }
#
# Materiales
#
scribo_material:
    pattern:  /mate
    defaults: { _controller: ScriboBundle:Material:index }
scribo_material_save:
    pattern:  /mate/save
    defaults: { _controller: ScriboBundle:Material:save }
scribo_material_save:
    pattern:  /mate/save
    defaults: { _controller: ScriboBundle:Material:save }
scribo_material_list:
    pattern:  /mate/enum
    defaults: { _controller: ScriboBundle:Material:enum }
scribo_material_get:
    pattern:  /mate/get
    defaults: { _controller: ScriboBundle:Material:get }
scribo_material_del:
    pattern:  /mate/del
    defaults: { _controller: ScriboBundle:Material:del }
#
# Acabados
#
scribo_acabado:
    pattern:  /acab
    defaults: { _controller: ScriboBundle:Acabado:index }
scribo_acabado_save:
    pattern:  /acab/save
    defaults: { _controller: ScriboBundle:Acabado:save }
scribo_acabado_save:
    pattern:  /acab/save
    defaults: { _controller: ScriboBundle:Acabado:save }
scribo_acabado_list:
    pattern:  /acab/enum
    defaults: { _controller: ScriboBundle:Acabado:enum }
scribo_acabado_get:
    pattern:  /acab/get
    defaults: { _controller: ScriboBundle:Acabado:get }
scribo_acabado_del:
    pattern:  /acab/del
    defaults: { _controller: ScriboBundle:Acabado:del }
#
# Tintas
#
scribo_tinta:
    pattern:  /tint
    defaults: { _controller: ScriboBundle:Tinta:index }
scribo_tinta_save:
    pattern:  /tint/save
    defaults: { _controller: ScriboBundle:Tinta:save }
scribo_tinta_save:
    pattern:  /tint/save
    defaults: { _controller: ScriboBundle:Tinta:save }
scribo_tinta_list:
    pattern:  /tint/enum
    defaults: { _controller: ScriboBundle:Tinta:enum }
scribo_tinta_get:
    pattern:  /tint/get
    defaults: { _controller: ScriboBundle:Tinta:get }
scribo_tinta_del:
    pattern:  /tint/del
    defaults: { _controller: ScriboBundle:Tinta:del }
#
# Orden Tipo 1
#
scribo_uno:
    pattern:  /uno
    defaults: { _controller: ScriboBundle:Uno:index }
scribo_uno_findcli:
    pattern:  /uno/ordclient
    defaults: { _controller: ScriboBundle:Uno:fcli }
scribo_uno_findmate:
    pattern:  /uno/ordmaterial
    defaults: { _controller: ScriboBundle:Uno:fmate }
scribo_uno_findtinta:
    pattern:  /uno/ordtinta
    defaults: { _controller: ScriboBundle:Uno:ftinta }
scribo_uno_findacabado:
    pattern:  /uno/ordacabado
    defaults: { _controller: ScriboBundle:Uno:facabado }
scribo_uno_save:
    pattern:  /uno/save
    defaults: { _controller: ScriboBundle:Uno:save }
scribo_uno_docu:
    pattern:  /uno/{id}/docu
    defaults: { _controller: ScriboBundle:Uno:docu }
